# -*- coding: utf-8 -*-
"""Aula 06 - 21/03 -- JoaoSassi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDBa43SOxwOKnScreX00jDKh1bghTScy

# Aula 06 - Intepretação Semântica e Gramáticas

### EX 1 - Representação do significado das palavras e frases com redes Semânticas
"""

import nltk
from nltk.corpus import wordnet

# banco de dados para utilizacao do sinônimos
nltk.download('wordnet' )
# Corpus que relaciona as palavras em diversos idiomas - traducao automatica
nltk.download('omw-1.4')

sinonimos = wordnet.synsets("carro", lang="por")

print(sinonimos)

for s in sinonimos:
  print(s.lemmas()[0].name())
# s.lemmas(): Obtem a lista de lemmas (formas basicas das palavras) no synset atual.
# [0]: Pega o primeiro lemma da lista.
# .name(): Obtém o nome do lemma (o sinônimo em si).
# print(): Imprime o sinônimo na tela.

"""### EX 2 - Representação do significado das palavras e frases por Vetores (Embeddings)"""

#!pip install spacy
!python -m spacy download pt_core_news_md

import spacy

nlp = spacy. load('pt_core_news_md' )

palavra1 = nlp('rei')
palavra2 = nlp('rainha' )

print (palavra1.similarity(palavra2))

"""### EX 03 - Análise sintática"""

!python -m spacy download pt_core_news_sm

import spacy
from spacy import displacy

nlp = spacy. load("pt_core_news_sm")
frase = "O cachorro correu no parque."
doc = nlp(frase)

displacy.render(doc, style='dep', jupyter=True)

"""### EX 04 - Ontologia"""

!pip install owlready2

from owlready2 import *

onto = get_ontology("http://exemplo.com/minha_ontologia.owl")

with onto:
  class Animal(Thing): pass
  class Mamifero(Animal): pass
  class Cachorro(Mamifero): pass
  class Gato(Mamifero): pass

onto.save("minha_ontologia.owl")

"""### Estudo de Caso 01 - Aplicação de análise semântica dem um corpus"""

import spacy
import nltk
import pandas as pd

from nltk.corpus import wordnet as wn

nltk.download('wordnet')
nltk.download('omw-1.4')

nlp = spacy. load("en_core_web_sm")

text = "Apple is looking at buying U.K. startup for $1 billion. Steve Jobs founded A"

doc = nlp(text)
syntactic_data = []

for token in doc:
  syntactic_data.append({
    "Token": token.text,
    "Pos-Tag": token.pos_,
    "Dependência": token.dep_,
    "Cabeça da Dep": token.head.text
  })

df_syntactic = pd.DataFrame(syntactic_data)
print("\n Análise Sintática:")
print(df_syntactic)

# 2. Reconhecimento de Entidades Nomeadas (NER)
entities_data = []

for ent in doc.ents:
  entities_data. append({
    "Entidade": ent.text,
    "Tipo": ent.label
  })

df_entities = pd.DataFrame(entities_data)
print("\n Reconhecimento de Entidades:")
print(df_entities)

# 3. Análise Semântica com WordNet
semantic_data = []

for token in doc:
  synsets = wn.synsets(token. text)
  if synsets:
    semantic_data.append({
      "Palavra": token.text,
      "Significado": synsets[0].definition(),
      "Exemplo": synsets[0]. examples ()
    })

df_semantic = pd.DataFrame(semantic_data)
print("\n Análise Semântica:")
print(df_semantic)