# -*- coding: utf-8 -*-
"""Aula 02 - 21/02 -- Joao Sassi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SR6MIPuuuSIS8wOUttRAkG0EZOiY47uc

# 1 - Sintaxe Básica e Estrutura do Código em Python
"""

print("Codiguin")

print('Isso rodará')

"""# 2 - Atribuição de variáveis."""

carros = 100
espacoEmUmCarro = 4.0
motoristas = 30
passageiros = 90
carrosNaoDirigidos = carros - motoristas
carrosDirigidos = motoristas
capacidadeCarona = carrosDirigidos * espacoEmUmCarro
mediaPassageirosPorCarro = passageiros / carrosDirigidos

print("Há", carros, "carros disponíveis.")
print("Há apenas", motoristas, "motoristas disponíveis.")
print("Haverá", carrosNaoDirigidos, "carros vazios hoje.")
print("Podemos transportar", capacidadeCarona, "pessoas hoje.")
print("Temos", passageiros, "passageiros para a carona hoje.")
print("Precisamos colocar cerca de", mediaPassageirosPorCarro, "em cada carro.")
print(10/5)

"""# 3 - Entrada e saída de dados"""

print("Quantos anos você tem?", end=' ')
idade = input()

print("Qual a sua altura (cm)?", end=' ')
altura = input()

print("Quanto você pesa?", end=' ')
peso = input()

print(f"Então, você tem {idade} anos, {altura} cm de altura e pesa {peso}.")

"""# 4 - Operadores"""

print("Agora vou contar minhas galinhas:")
print("Galinhas", 25 + 30 / 6)
print("Galos", 100.0 - 25 * 3 % 4)

print("Agora vou contar os ovos:")
print(3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6)

print("É verdade que 3 + 2 < 5 - 7?")
print(3 + 2 < 5 - 7)

print("Quanto é 3 + 2?", 3 + 2)
print("Quanto é 5 - 7?", 5 - 7)
print("Ah, é por isso que é Falso.")

print("Que tal mais algumas comparações?")

print("É maior?", 5 > -2)
print("É maior ou igual?", 5 >= -2)
print("É menor ou igual?", 5 <= -2)

"""# 5 - Estruturas Condicionais"""

pessoas = 30
carros = 40
caminhoes = 15

if carros > pessoas:
    print("Devemos pegar os carros.")
elif carros < pessoas:
    print("Não devemos pegar os carros.")
else:
    print("Não podemos decidir.")

if caminhoes > carros:
    print("São caminhões demais.")
elif caminhoes < carros:
    print("Talvez possamos pegar os caminhões.")
else:
    print("Ainda não podemos decidir.")

if pessoas > caminhoes:
    print("Certo, vamos apenas pegar os caminhões.")
else:
    print("Tudo bem, então vamos ficar em casa.")

"""# 6 - Laços de Repetição"""

i = 0
numeros = []

while i < 6:
    print(f"No topo, i é {i}")
    numeros.append(i)

    i = i + 1
    print("Números agora:", numeros)
    print(f"Na parte inferior, i é {i}")

print("Os números:")

for num in numeros:
    print(num)

"""# 7 - Listas e Strings"""

contagem = [1, 2, 3, 4, 5]
frutas = ['maçãs', 'laranjas', 'peras', 'damascos']
troco = [1, 'centavos', 2, 'dimes', 3, 'quarters']

for numero in contagem:
    print(f"Este é o número {numero}")

for fruta in frutas:
    print(f"Uma fruta do tipo: {fruta}")

for i in troco:
    print(f"Eu tenho {i}")

elementos = []

for i in range(0, 6):
    print(f"Adicionando {i} à lista.")
    elementos.append(i)

for i in elementos:
    print(f"O elemento era: {i}")

"""# Exercícios

## Exercício 1
"""

comprimento = float(input("Digite o comprimento da caixa: "))
largura = float(input("Digite a largura da caixa: "))
altura = float(input("Digite a altura da caixa: "))

volume = comprimento * largura * altura
print(f"O volume da caixa é: {volume}")

"""## Exercício 2"""

texto = input("Digite um texto: ")
palavras = texto.split()
print(f"O texto contém {len(palavras)} palavras.")

"""## Exercício 3"""

texto_original = input("Digite um texto: ")
palavra_busca = input("Digite a palavra que deseja substituir: ")
palavra_substituir = input("Digite a nova palavra: ")

texto_modificado = texto_original.replace(palavra_busca, palavra_substituir)
print("Texto modificado:", texto_modificado)

"""## Exercício 4"""

texto = input("Digite um texto com várias frases separadas por ponto: ")
frases = texto.split('.')
print("Frases separadas:")
for frase in frases:
    if frase.strip():
        print(frase.strip())

"""## Exercício 5"""

a = int(input("Digite o primeiro número: "))
b = int(input("Digite o segundo número: "))
c = int(input("Digite o terceiro número: "))

numeros = [a, b, c]
numeros.sort()
print("Números em ordem crescente:", numeros)

"""## Exercício 6"""

valores = []
for i in range(4):
    valores.append(int(input(f"Digite o {i+1}º valor: ")))

print("Valores divisíveis por 2 e 3:")
for valor in valores:
    if valor % 2 == 0 and valor % 3 == 0:
        print(valor)

"""## Exercício 7"""

print("Números divisíveis por 4 e menores que 200:")
for i in range(4, 200, 4):
    print(i)