# -*- coding: utf-8 -*-
"""Projeto 01 - Joao Pedro Sassi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hfTZJ4_2xDuVGpgmwlEPdKX9JFjC00C

# Projeto 1 - Análise quantitativa de Corpus
"""

def ler(nome_arquivo):
  arquivo = open(nome_arquivo,'r', encoding='utf-8')
  conteudo_arq = arquivo.read()
  arquivo.close()
  return conteudo_arq

texto = ler('/content/drive/MyDrive/FatecMaua/6_Sem/ProcessamentoLinguagemNatural/2025.05 Ubirajara.txt')
print(len(texto))

"""### Primeira Etapa - Buscador de palavras"""

def buscador(alvo, texto):
  texto = texto.replace('\n', ' ')
  texto = texto.replace('\t', ' ')

  ocorrencias = []
  encontrado_aqui = texto.find(alvo, 0)

  while encontrado_aqui > 0:
    pos_inicial = encontrado_aqui - (40 - len(alvo))
    trecho = texto[pos_inicial: pos_inicial + 80]

    ocorrencias.append(trecho)

    encontrado_aqui = texto.find(alvo, encontrado_aqui + 1)

  return ocorrencias

resultados = buscador('peito', texto)
for trecho in resultados:
  print(trecho)

"""### Segunda Etapa - Limpeza dos Corpus"""

palavras = texto.split()

def limpar(lista):
  lixo = '.,:;?!"`()[]{}/\|@#$%"&*-'
  quase_limpo = [x.strip(lixo).lower() for x in lista]
  return [x for x in quase_limpo if x.isalpha() or '-' not in x]

print(len(palavras))
palavras = limpar(palavras)
print(len(palavras))

"""### Quantidade de Palavras"""

vocabulario = set(palavras)
len(vocabulario)

# Riqueza textual
riqueza = len(vocabulario) / len(palavras)
print(riqueza)

# Dicionario do texto
from collections import defaultdict

def ocorrencias (lista_palavras):
  dicionario = defaultdict(int)
  for p in lista_palavras:
    dicionario[p] += 1

  return dicionario

dic = ocorrencias(palavras)
mf = sorted(dic.items(), key=lambda tupla:tupla[1], reverse = True)[:50]
for palavra, n in mf:
    print(palavra, '\t', n)

import nltk
nltk.download('stopwords')
vazias = nltk.corpus.stopwords.words('portuguese')

frequentes_plenas = [x for x in mf if x[0].lower() not in vazias]
frequentes_plenas